// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5mFKLu6gN-M6nl8UqVNkWOBeYrzDMJ3Q',
    appId: '1:29126714665:android:b0ed728a37e63193b9c338',
    messagingSenderId: '29126714665',
    projectId: 'ntripi',
    storageBucket: 'ntripi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB88Sv7fgqZfmTgbEHFkSYtWMFzMDNiRE',
    appId: '1:29126714665:ios:87d9f65892e26eb8b9c338',
    messagingSenderId: '29126714665',
    projectId: 'ntripi',
    storageBucket: 'ntripi.firebasestorage.app',
    androidClientId: '29126714665-ma7ilq9omd9g8nh34hs5oufvhhqkakrq.apps.googleusercontent.com',
    iosClientId: '29126714665-8n68nlct0m8edp04b6obslteslqtitdq.apps.googleusercontent.com',
    iosBundleId: 'com.ismailkarroud.ntripi',
  );
}
