"""add_itinerary_ratings_table

Revision ID: 07035928fd6c
Revises: c3d2e1f0a9b8
Create Date: 2026-04-19 12:21:08.404621+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07035928fd6c'
down_revision: Union[str, None] = 'c3d2e1f0a9b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('itinerary_ratings',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('itinerary_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stars', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('stars BETWEEN 1 AND 5', name='ck_rating_stars'),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'user_id', name='uq_itinerary_rating')
    )
    op.create_index(op.f('ix_itinerary_ratings_itinerary_id'), 'itinerary_ratings', ['itinerary_id'], unique=False)
    op.add_column('itineraries', sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('itineraries', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itineraries', 'rating_count')
    op.drop_column('itineraries', 'rating_avg')
    op.drop_index(op.f('ix_itinerary_ratings_itinerary_id'), table_name='itinerary_ratings')
    op.drop_table('itinerary_ratings')
    # ### end Alembic commands ###
