"""ratings_set_null_and_tos_accepted_at

Migration: change itinerary_ratings.user_id from ON DELETE CASCADE
to ON DELETE SET NULL, and add tos_accepted_at to users.

Legal basis (GDPR Article 17 — Right to Erasure):
  A star rating score (1–5 integer) linked to a NULL user_id is
  anonymized data. It contains no information that can identify
  the former user. Anonymized data falls outside GDPR scope and
  may be retained.

  Users consent to this behavior at registration via ToS acceptance
  (tos_accepted_at timestamp recorded on the user row).

  The account deletion flow warns the user explicitly that their
  ratings will be anonymized, not deleted.

Revision ID: e493ea56a71b
Revises: 07035928fd6c
Create Date: 2026-04-19 13:26:07.146907+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e493ea56a71b'
down_revision: Union[str, None] = '07035928fd6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('itinerary_ratings', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('itinerary_ratings_user_id_fkey'), 'itinerary_ratings', type_='foreignkey')
    op.create_foreign_key(None, 'itinerary_ratings', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('tos_accepted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tos_accepted_at')
    op.drop_constraint(None, 'itinerary_ratings', type_='foreignkey')
    op.create_foreign_key(op.f('itinerary_ratings_user_id_fkey'), 'itinerary_ratings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('itinerary_ratings', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
